### ISSUE TITLE
What

### ISSUE THREAD

**Issue by LHolten** [fee1-dead/phtm#1]
You have defined:
```rust
pub type CovariantOverLt<'co> = PhantomData<ContravariantOver<&'co ()>>;
```
But that should be:
```rust
pub type CovariantOverLt<'co> = CovariantOver<&'co ()>;
```
This library had one job..

**Comment by fee1-dead** [comment]
:/ what was I doing when I wrote that.. Do you still want to use this library? I could change this and also maybe add some tests..

**Comment by LHolten** [comment]
If you can guarantee that the library is correct, then I would like to use it yes.
I think it helps with readability.

**Comment by fee1-dead** [comment]
I've updated the crate. Looking back I think the crate doesn't have much of a use since it emphasizes variance over the ownership/borrowing model. I think the latter is probably more important. If you are making a smart pointer that owns a type, then you should use `PhantomData<T>`. If you are making a function sort of type then you use `PhantomData<fn() -> T>`. Therefore you wouldn't need to understand variance to understand `PhantomData` (just need subtyping knowledge)

I wrote this library as a way to consolidate my understanding of variance and subtyping and thought it would be nice to have type aliases for everything.

Anyways, I think the real value this crate offers is documentation. Feel free to copy the documentation and type aliases to your own crate. You don't have to credit me.

edit: nah actually. The documentation isn't much. It's just me restating the rustonomicon and other stuff. Nevermind then.
